# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160128_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_accept',
            field=models.BooleanField(verbose_name='Accepted?'),
        ),
    ]
