# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160128_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='c_accept',
            new_name='accept',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='c_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='c_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='c_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='c_website',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='c_title',
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=0, max_length=200, verbose_name='Comment Title'),
            preserve_default=False,
        ),
    ]
