# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabi', '0002_auto_20160105_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=0),
        ),
    ]
