# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabi', '0004_auto_20160105_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summery',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
