# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabi', '0006_authors_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='صورة الكاتب'),
            preserve_default=False,
        ),
    ]
