# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitabi', '0007_authors_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='facebook',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authors',
            name='twitter',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authors',
            name='website',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
